# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8208b222da539eccba6368ae66b94298569e60d37355f79f4ca7b1c9d8a81e0a87412788a1373bdaeafb6a306242f4fdac151670ac0c54fcf3905a6b52f7453c

test:
  secret_key_base: 47bb68cc179da6b73d2e6928204a3ddb26c2b5e689ab8451025eb634c255f1c412934be86cd983b5cf0037eae92fe904835d19d7091605be92975940e4931e91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
